language: scala

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/1.0/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2

script:
- sbt +clean
- sbt +test

scala:
- 2.11.8

jdk:
- oraclejdk8

before_script:
- mkdir $TRAVIS_BUILD_DIR/tmp
- export SBT_OPTS="-Djava.io.tmpdir=$TRAVIS_BUILD_DIR/tmp"

sudo: false