language: scala

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/1.0/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2

script:
- sbt ++$TRAVIS_SCALA_VERSION! test

scala:
- 2.11.12
- 2.12.9
- 2.13.0

jdk:
- openjdk8
- openjdk11

before_script:
- export AWS_SECRET_KEY=foo
- export AWS_ACCESS_KEY_ID=bar
- mkdir $TRAVIS_BUILD_DIR/tmp
- export SBT_OPTS="-Djava.io.tmpdir=$TRAVIS_BUILD_DIR/tmp"

sudo: false

branches:
  only:
    - master